# Generated by Django 5.2.3 on 2025-06-27 06:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="InsuranceDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("file_path", models.CharField(max_length=500)),
                ("original_filename", models.CharField(max_length=200)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("processed", models.BooleanField(default=False)),
                ("total_chunks", models.IntegerField(default=0)),
            ],
            options={
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="InsuranceQuery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("query_text", models.TextField()),
                ("response_text", models.TextField()),
                ("retrieved_chunks", models.JSONField(default=list)),
                ("query_time", models.DateTimeField(auto_now_add=True)),
                ("processing_time", models.FloatField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-query_time"],
            },
        ),
        migrations.CreateModel(
            name="DocumentChunk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("chunk_id", models.CharField(max_length=100)),
                ("content", models.TextField()),
                (
                    "strategy",
                    models.CharField(
                        choices=[
                            ("policy", "Policy-based"),
                            ("semantic", "Semantic"),
                            ("header", "Header-based"),
                        ],
                        max_length=20,
                    ),
                ),
                ("metadata", models.JSONField(default=dict)),
                ("embedding_vector", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chunks",
                        to="insurance.insurancedocument",
                    ),
                ),
            ],
            options={
                "ordering": ["chunk_id"],
                "unique_together": {("document", "chunk_id")},
            },
        ),
    ]
