# Generated by Django 5.2.3 on 2025-06-29 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("insurance", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="documentchunk",
            name="insurance_type",
            field=models.CharField(
                choices=[
                    ("health", "Health Insurance"),
                    ("car", "Car Insurance"),
                    ("life", "Life Insurance"),
                    ("home", "Home Insurance"),
                ],
                default="health",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="insurancedocument",
            name="insurance_type",
            field=models.CharField(
                choices=[
                    ("health", "Health Insurance"),
                    ("car", "Car Insurance"),
                    ("life", "Life Insurance"),
                    ("home", "Home Insurance"),
                ],
                default="health",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="insurancequery",
            name="insurance_type",
            field=models.CharField(
                choices=[
                    ("health", "Health Insurance"),
                    ("car", "Car Insurance"),
                    ("life", "Life Insurance"),
                    ("home", "Home Insurance"),
                ],
                default="health",
                max_length=20,
            ),
        ),
    ]
