# Generated by Django 5.2 on 2025-06-28 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicalrecord',
            name='summary',
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='summary_doctor',
            field=models.TextField(default='Older Version'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='summary_patient',
            field=models.TextField(default='Older Version'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='markdown_summary',
            field=models.TextField(default='Older Version'),
            preserve_default=False,
        ),
    ]
