# Generated by Django 5.2 on 2025-06-28 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medical_app', '0002_remove_medicalrecord_summary_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicalrecord',
            old_name='summary_doctor',
            new_name='insurance_summary',
        ),
        migrations.RemoveField(
            model_name='medicalrecord',
            name='summary_patient',
        ),
    ]
