# Generated by Django 5.2.3 on 2025-06-29 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "medical_app",
            "0003_rename_summary_doctor_medicalrecord_insurance_summary_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="medicalrecord",
            name="insurance_type",
            field=models.CharField(
                choices=[
                    ("health", "Health Insurance"),
                    ("car", "Car Insurance"),
                    ("life", "Life Insurance"),
                    ("home", "Home Insurance"),
                ],
                default="health",
                max_length=50,
            ),
        ),
    ]
